package com.knowledgegraph.model;

public enum EdgeType {
    // Organizational relationships
    AFFILIATED_WITH,
    WORKS_AT,
    EMPLOYED_BY,
    FOUNDED,
    FOUNDED_BY,
    OWNS,
    OWNED_BY,
    MANAGES,
    MANAGED_BY,
    
    // Intellectual relationships
    AUTHORED,
    AUTHORED_BY,
    CREATED,
    CREATED_BY,
    DEVELOPED,
    DEVELOPED_BY,
    INVENTED,
    INVENTED_BY,
    DISCOVERED,
    DISCOVERED_BY,
    PROPOSED,
    PROPOSED_BY,
    
    // Academic/Research relationships
    STUDIED,
    STUDIED_BY,
    TEACHES,
    TAUGHT_BY,
    INFLUENCED,
    INFLUENCED_BY,
    CITED_BY,
    CITES,
    REFERENCES,
    BUILDS_ON,
    CONTRADICTS,
    SUPPORTS,
    CRITIQUES,
    
    // Temporal relationships
    PRECEDED_BY,
    PRECEDES,
    OCCURRED_DURING,
    HAPPENED_AT,
    
    // Spatial relationships
    LOCATED_IN,
    LOCATED_AT,
    NEAR,
    
    // Hierarchical relationships
    PART_OF,
    CONTAINS,
    PARENT_OF,
    CHILD_OF,
    SUBCATEGORY_OF,
    
    // Event relationships
    PARTICIPATED_IN,
    ATTENDED,
    ORGANIZED,
    ORGANIZED_BY,
    PRESENTED_AT,
    
    // Production relationships
    PRODUCED,
    PRODUCED_BY,
    MANUFACTURED_BY,
    PUBLISHED_BY,
    
    // Comparison relationships
    SIMILAR_TO,
    DIFFERENT_FROM,
    SAME_AS,
    OPPOSITE_OF,
    
    // Causal relationships
    CAUSES,
    CAUSED_BY,
    LEADS_TO,
    RESULTS_IN,
    DERIVES_FROM,
    
    // Generic relationships
    RELATED_TO,
    ASSOCIATED_WITH,
    CONNECTED_TO,
    DEPENDS_ON,
    USES,
    USED_BY,
    
    // Educational/Academic specific
    TOOK_EXAM,
    SCORED,
    RECEIVED_GRADE,
    ENROLLED_IN,
    GRADUATED_FROM,
    MAJORED_IN,
    MINORED_IN,
    RECEIVED_DEGREE,
    RECEIVED_CERTIFICATE,
    RECEIVED_AWARD,
    STUDIES_AT,
    RESEARCHES,
    ADVISES,
    ADVISED_BY,
    COLLABORATES_WITH,
    CO_AUTHORED,
    PEER_REVIEWED,
    SUBMITTED_TO,
    ACCEPTED_BY,
    REJECTED_BY,
    
    // Personal/Identity
    HAS_IDENTIFIER,
    HAS_ID,
    HAS_NAME,
    KNOWN_AS,
    ALIAS_OF,
    LIVES_AT,
    RESIDED_AT,
    BORN_IN,
    BORN_ON,
    DIED_IN,
    DIED_ON,
    
    // Professional
    REPORTS_TO,
    SUPERVISES,
    HIRED,
    HIRED_BY,
    FIRED,
    FIRED_BY,
    PROMOTED,
    PROMOTED_BY,
    TRANSFERRED_TO,
    WORKED_ON,
    CONTRIBUTED_TO,
    LED,
    MEMBER_OF,
    BOARD_MEMBER_OF,
    INVESTOR_IN,
    FUNDED,
    FUNDED_BY,
    
    // Legal/Ownership
    OWNS_STAKE_IN,
    ACQUIRED,
    ACQUIRED_BY,
    MERGED_WITH,
    SPUN_OFF_FROM,
    LICENSED_TO,
    LICENSED_FROM,
    SUED,
    SUED_BY,
    SETTLED_WITH,
    REGULATED_BY,
    COMPLIES_WITH,
    VIOLATES,
    
    // Communication/Information
    MENTIONED_IN,
    QUOTED_IN,
    RESPONDED_TO,
    REPLIED_TO,
    COMMENTED_ON,
    SHARED,
    FORWARDED,
    TAGGED_IN,
    LINKS_TO,
    
    // Process/Workflow
    PRECONDITION_OF,
    POSTCONDITION_OF,
    TRIGGERS,
    TRIGGERED_BY,
    ENABLES,
    BLOCKS,
    BLOCKED_BY,
    REQUIRES,
    REQUIRED_BY,
    OPTIONAL_FOR,
    ALTERNATIVE_TO,
    
    // Measurement/Comparison
    GREATER_THAN,
    LESS_THAN,
    EQUAL_TO,
    PROPORTIONAL_TO,
    INVERSELY_PROPORTIONAL_TO,
    CORRELATED_WITH,
    BENCHMARKED_AGAINST,
    
    // Domain specific
    PATIENT_OF,
    TREATS,
    DIAGNOSED_WITH,
    PRESCRIBED,
    PRESCRIBED_BY,
    SYMPTOM_OF,
    SIDE_EFFECT_OF,
    CONTRAINDICATED_WITH,
    INTERACTS_WITH,
    
    // Version/Evolution
    VERSION_OF,
    UPGRADED_TO,
    DOWNGRADED_TO,
    REPLACED_BY,
    REPLACES,
    DEPRECATED_BY,
    FORK_OF,
    BRANCH_OF,
    MERGED_INTO,
    
    // Classification
    INSTANCE_OF,
    TYPE_OF,
    KIND_OF,
    EXAMPLE_OF,
    CATEGORY_OF,
    CLASSIFIED_AS,
    LABELED_AS,
    TAGGED_AS,
    
    // Emotional/Social
    LIKES,
    DISLIKES,
    LOVES,
    HATES,
    FEARS,
    TRUSTS,
    DISTRUSTS,
    RESPECTS,
    ADMIRES,
    ENVIES,
    FRIEND_OF,
    ENEMY_OF,
    RIVAL_OF,
    PARTNER_OF,
    MARRIED_TO,
    DIVORCED_FROM,
    SIBLING_OF,
    ANCESTOR_OF,
    DESCENDANT_OF
}